---
- name: Get id of credential_type Source Control
  ansible.builtin.set_fact:
    scm_type_id: "{{ __aap_credential_types | selectattr('namespace', 'eq', 'scm') | map(attribute='id') | first }}"

- name: Get a list of scm credentials
  ansible.builtin.set_fact:
    git_credential: "{{ __aap_credentials | selectattr('credential_type', 'eq', scm_type_id | int) | map(attribute='name') }}"

- name: Create a valid git credential
  ansible.controller.credential:
    controller_host: "{{ controller_host }}"
    controller_oauthtoken: "{{ controller_token }}"
    validate_certs: "{{ controller_validate_certs }}"
    name: "{{ cur_credential.name }}"
    description: "{{ cur_credential.description }}"
    organization: "{{ cur_credential.organization }}"
    credential_type: "Source Control"
    inputs: "{{ cur_credential.inputs }}"
    state: present
  when: cur_credential.name not in git_credential
