---
# tasks file for manage_hub_exec_envs
- name: Check that a hub host is specified
  ansible.builtin.assert:
    that: hub_host | default('') | length
    fail_msg: No hub_host defined; aborting
    success_msg: hub_host set to {{ hub_host }}

- name: Check that a hub admin user is specified
  ansible.builtin.assert:
    that: hub_admin_user | default('') | length
    fail_msg: No hub_admin_user defined; aborting
    success_msg: hub_admin_user set to {{ hub_admin_user }}

- name: Configure the registries for execution environments
  loop: "{{ hub_ee_registries }}"
  loop_control:
    loop_var: current_reg
    label: current_reg.label
  redhat_cop.ah_configuration.ah_ee_registry:
    ah_host: "{{ hub_host }}"
    ah_username: "{{ hub_admin_user }}"
    ah_password: "{{ hub_admin_password }}"
    validate_certs: "{{ hub_validate_certs | default(true) }}"
    name: "{{ current_reg.name }}"
    url: "{{ current_reg.proto }}://{{ current_reg.host }}"
    username: "{{ current_reg.username }}"
    password: "{{ current_reg.password }}"
    state: present

- name: Add the execution environments to the hub
  when: current_ee.label is defined
  loop: "{{ hub_ee_images }}"
  loop_control:
    loop_var: current_ee
    label: current_ee.image
  redhat_cop.ah_configuration.ah_ee_repository:
    ah_host: "{{ hub_host }}"
    ah_username: "{{ hub_admin_user }}"
    ah_password: "{{ hub_admin_password }}"
    validate_certs: "{{ hub_validate_certs | default(true) }}"
    name: "{{ current_ee.namespace }}/{{ current_ee.image }}"
    description: "{{ current_ee.description }}"
    include_tags: "{{ current_ee.tags | default(omit) }}"
    upstream_name: "{{ current_ee.namespace }}/{{ current_ee.image }}"
    registry: "{{ hub_ee_registries | selectattr('label', 'eq', current_ee.label) | map(attribute='name') | first }}"
    state: present

- name: Sync the registries
  loop: "{{ hub_ee_registries }}"
  loop_control:
    loop_var: current_reg
    label: current_reg.label
  redhat_cop.ah_configuration.ah_ee_registry_sync:
    ah_host: "{{ hub_host }}"
    ah_username: "{{ hub_admin_user }}"
    ah_password: "{{ hub_admin_password }}"
    validate_certs: "{{ hub_validate_certs | default(true) }}"
    name: "{{ current_reg.name }}"
    wait: "{{ hub_ee_sync_wait }}"

- name: Sync the execution environments on the hub
  when: current_ee.label is defined
  loop: "{{ hub_ee_images }}"
  loop_control:
    loop_var: current_ee
    label: current_ee.image
  redhat_cop.ah_configuration.ah_ee_repository_sync:
    ah_host: "{{ hub_host }}"
    ah_username: "{{ hub_admin_user }}"
    ah_password: "{{ hub_admin_password }}"
    validate_certs: "{{ hub_validate_certs | default(true) }}"
    name: "{{ current_ee.namespace }}/{{ current_ee.image }}"
    wait: "{{ hub_ee_sync_wait }}"
