---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.22.2 # put latest release tag from https://github.com/ansible/ansible-lint/releases/
    hooks:
      - id: ansible-lint
        name: Ansible-lint
        description: This hook runs ansible-lint.
        entry: /usr/bin/ansible-lint -v --force-color
        language: python
        pass_filenames: false
        always_run: true
        additional_dependencies:
          - ansible-core>=2.13.3
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: yamllint
        description: This hook runs yamllint.
        entry: yamllint
        language: python
        types: [file, yaml]
