---
- name: Configure all remotes
  ansible.hub.collection_remote:
    ah_host: "{{ platform_host }}"
    ah_username: "{{ aap_admin_user }}"
    ah_password: "{{ aap_admin_password }}"
    validate_certs: "{{ aap_validate_certs | default(true) }}"
    name: "{{ current_repo.name }}"
    url: "{{ current_repo.url }}"
    auth_url: "{{ current_repo.auth_url | default(omit) }}"
    download_concurrency: "{{ current_repo.download_concurrency | default(omit) }}"
    max_retries: "{{ current_repo.max_retries | default(omit) }}"
    password: "{{ current_repo.password | default(omit) }}"
    proxy_password: "{{ aap_proxy_password | default(omit) }}"
    proxy_url: "{{ aap_proxy_url | default(omit) }}"
    proxy_username: "{{ aap_proxy_username | default(omit) }}"
    rate_limit: "{{ current_repo.rate_limit | default(omit) }}"
    request_timeout: "{{ current_repo.request_timeout | default(omit) }}"
    requirements: "{{ current_repo.requirements | default(omit) }}"
    signed_only: "{{ current_repo.signed_only | default(omit) }}"
    sync_dependencies: "{{ current_repo.sync_dependencies | default(omit) }}"
    token: "{{ current_repo.token | default(omit) }}"
    state: "{{ current_repo.state | default('present') }}"
  loop: "{{ aap_collection_repos | default([]) }}"
  loop_control:
    loop_var: current_repo
    label: "{{ current_repo.name }}"

- name: Configure all repositories
  ansible.hub.collection_repository:
    ah_host: "{{ platform_host }}"
    ah_username: "{{ aap_admin_user }}"
    ah_password: "{{ aap_admin_password }}"
    validate_certs: "{{ aap_validate_certs | default(true) }}"
    name: "{{ current_repo.name }}"
    description: "{{ current_repo.description | default(omit) }}"
    interval: "{{ current_repo.interval | default(omit) }}"
    private: "{{ current_repo.private | default(omit) }}"
    remote: "{{ current_repo.name }}"
    retain_repo_versions: "{{ current_repo.retain_repo_versions | default(omit) }}"
    update_repo: false
    wait: "{{ aap_reposync_wait | default(omit) }}"
    state: "{{ current_repo.state | default('present') }}"
  loop: "{{ aap_collection_repos | default([]) }}"
  loop_control:
    loop_var: current_repo
    label: "{{ current_repo.name }}"
