---
# tasks file for manage_hub_collections
- name: Perform input variable validation
  ansible.builtin.include_tasks:
    file: validate_input.yml

- name: Sync collection repositories
  ansible.builtin.include_tasks:
    file: sync.yml
