---
- name: Sync all repositories
  ansible.hub.collection_repository_sync:
    ah_host: "{{ platform_host }}"
    ah_username: "{{ automationhub_admin_user }}"
    ah_password: "{{ automationhub_admin_password }}"
    validate_certs: "{{ aap_validate_certs | default(true) }}"
    name: "{{ current_repo.name }}"
    wait: "{{ aap_reposync_wait }}"
  loop: "{{ aap_collection_repos | default([]) }}"
  loop_control:
    loop_var: current_repo
    label: "{{ current_repo.name }}"
