---
- name: Get a list of execution environments from the PAH
  ansible.builtin.uri:
    url: "https://{{ automationhub_host }}/{{ __api_containers }}"
    user: "{{ automationhub_admin_user }}"
    password: "{{ automationhub_admin_password }}"
    method: GET
    force_basic_auth: true
    validate_certs: "{{ aap_validate_certs | default(true) }}"
  register: pah_images

- name: Get a list of container namespaces from the PAH
  ansible.builtin.uri:
    url: "https://{{ automationhub_host }}/{{ __api_container_namespaces }}"
    user: "{{ automationhub_admin_user }}"
    password: "{{ automationhub_admin_password }}"
    method: GET
    force_basic_auth: true
    validate_certs: "{{ aap_validate_certs | default(true) }}"
  register: pah_namespaces

- name: Create a list of execution environments that should exist
  ansible.builtin.set_fact:
    config_images: "{{ aap_ee_images | map(attribute='namespace') | zip(aap_ee_images | map(attribute='image')) | map('join', '/') }}"

- name: Create a list of namespace hrefs that should exist
  ansible.builtin.set_fact:
    config_namespaces: "{{ pah_namespaces['json']['results'] | selectattr('name', 'in', aap_ee_namespaces | default([])) | map(attribute='pulp_href') }}"

- name: Print images that can be deleted
  ansible.builtin.debug:
    msg: "Image {{ cur_image['name'] }} can be deleted"
  when:
    - cur_image['name'] not in config_images
    - cur_image['namespace'] not in config_namespaces
  loop: "{{ pah_images['json']['results'] }}"
  loop_control:
    loop_var: cur_image

- name: Remove the execution environments from the hub that should not exist
  infra.ah_configuration.ah_ee_repository:
    ah_host: "{{ automationhub_host }}"
    ah_username: "{{ automationhub_admin_user }}"
    ah_password: "{{ automationhub_admin_password }}"
    validate_certs: "{{ aap_validate_certs | default(true) }}"
    name: "{{ cur_image['name'] }}"
    state: absent
  when:
    - cur_image['name'] not in config_images
    - cur_image['namespace'] not in config_namespaces
  loop: "{{ pah_images['json']['results'] }}"
  loop_control:
    loop_var: cur_image
