---
# stand-alone sync tasks file for manage_hub_exec_envs
- name: Perform input variable validation
  ansible.builtin.include_tasks:
    file: input_validation.yml

- name: Sync execution environment repositories
  ansible.builtin.include_tasks:
    file: sync.yml
