---
- name: Sync the registries
  infra.ah_configuration.ah_ee_registry_sync:
    ah_host: "{{ automationhub_host }}"
    ah_username: "{{ aap_admin_user }}"
    ah_password: "{{ aap_admin_password }}"
    validate_certs: "{{ aap_validate_certs | default(true) }}"
    name: "{{ current_reg.name }}"
    wait: "{{ hub_ee_sync_wait }}"
  when: current_reg.state | default('present') == "present"
  loop: "{{ aap_ee_registries }}"
  loop_control:
    loop_var: current_reg
    label: current_reg.label

- name: Sync the execution environments on the hub
  infra.ah_configuration.ah_ee_repository_sync:
    ah_host: "{{ automationhub_host }}"
    ah_username: "{{ aap_admin_user }}"
    ah_password: "{{ aap_admin_password }}"
    validate_certs: "{{ aap_validate_certs | default(true) }}"
    name: "{{ current_ee.namespace }}/{{ current_ee.image }}"
    wait: "{{ hub_ee_sync_wait }}"
  when:
    - current_ee.label is defined
    - current_ee.state | default('present') == "present"
  loop: "{{ aap_ee_images }}"
  loop_control:
    loop_var: current_ee
    label: current_ee.image
