---
# tasks file for manage_hub_exec_envs
- name: Perform input variable validation
  ansible.builtin.include_tasks:
    file: validate_input.yml

- name: Sync execution environment repositories
  ansible.builtin.include_tasks:
    file: sync.yml
