---
- name: Check that a hub host is specified
  ansible.builtin.assert:
    that: platform_host | default('') | length
    fail_msg: "No platform_host defined; aborting"
    success_msg: "platform_host set to {{ platform_host }}"

- name: Check that a hub admin user is specified
  ansible.builtin.assert:
    that: automationhub_admin_user | default('') | length
    fail_msg: "No automationhub_admin_user defined; aborting"
    success_msg: "automationhub_admin_user set to {{ automationhub_admin_user }}"

- name: Check that a hub admin password is specified
  ansible.builtin.assert:
    that: automationhub_admin_password | default('') | length
    fail_msg: "No automationhub_admin_password defined; aborting"
    success_msg: "automationhub_admin_password defined"
