---
- name: Check that a controller host is specified
  ansible.builtin.assert:
    that: controller_host | default('') | length
    fail_msg: "No controller_host defined; aborting"
    success_msg: "controller_host set to {{ controller_host }}"

- name: Check that a controller admin user is specified
  ansible.builtin.assert:
    that: controller_username | default('') | length
    fail_msg: "No controller_username defined; aborting"
    success_msg: "controller_username set to {{ controller_username }}"

- name: Check that a controller admin password is specified
  ansible.builtin.assert:
    that: controller_password | default('') | length
    fail_msg: "No controller_password defined; aborting"
    success_msg: "controller_password defined"
