---
# tasks file for manage_hub_exec_envs
- name: Perform input variable validation
  ansible.builtin.include_tasks:
    file: input_validation.yml

- name: Retrieve authentication token from controller using username/password
  ansible.controller.token:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    description: "Token for automated organization configuration"
    scope: "write"
    state: present
    validate_certs: "{{ aap_validate_certs }}"
  no_log: true

- name: Configure execution environments
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Cleanup execution environments we do not need
  ansible.builtin.include_tasks:
    file: cleanup.yml

- name: Delete the authentication token with the token we created
  ansible.controller.token:
    controller_host: "{{ controller_host }}"
    controller_oauthtoken: "{{ controller_token }}"
    existing_token: "{{ controller_token }}"
    state: absent
    validate_certs: "{{ aap_validate_certs }}"
  when: controller_token is defined
