---
# defaults file for manage_hub_exec_envs
aap_ee_registries:
  - label: rh-registry
    name: "Red Hat Registry"
    host: registry.redhat.io
    user: "registry_user"
    token: "registry_token"

aap_ee_images:
  - namespace: ansible-automation-platform-25
    image: ee-supported-rhel9
    label: rh-registry
    name: Default execution environment - RHEL-9
    description: Red Hat Ansible Automation Platform Supported Execution Environment on RHEL-9
    tags:
      - latest
  - namespace: ansible-automation-platform-25
    image: ee-supported-rhel8
    label: rh-registry
    name: Default execution environment - RHEL-8
    description: Red Hat Ansible Automation Platform Supported Execution Environment on RHEL-8
  - namespace: ansible-automation-platform-25
    image: de-supported-rhel9
    label: rh-registry
    name: Default decision environment - RHEL-9
    description: Red Hat Ansible Automation Platform Supported Decision Environment on RHEL-9
    tags:
      - latest
  - namespace: ansible-automation-platform-25
    image: de-supported-rhel8
    label: rh-registry
    name: Default decision environment - RHEL-8
    description: Red Hat Ansible Automation Platform Supported Decision Environment on RHEL-8

aap_control_plane_ee: ansible-automation-platform-25/ee-supported-rhel9
