---
- name: Create a list of execution environments that should exist
  ansible.builtin.set_fact:
    config_images: >
      {{ config_images | default([]) +
      [aap_main_url + '/' + current_ee.namespace + '/' + current_ee.image + ':' + current_ee.tag | default('latest')] }}
  loop: "{{ aap_container_images | selectattr('type', 'eq', 'execution') }}"
  loop_control:
    loop_var: current_ee
    label: "{{ current_ee.image }}"

- name: Print images that can be deleted
  ansible.builtin.debug:
    msg: "Image {{ cur_image['name'] }} can be deleted"
  when:
    - cur_image['image'] not in config_images
    - (cur_image['image'] | split('/'))[1] not in aap_container_namespaces
    - cur_image['name'] not in aap_reserved_images
  loop: "{{ __aap_ee_images }}"
  loop_control:
    loop_var: cur_image

- name: Remove the execution environments from the controller that should not exist
  ansible.controller.execution_environment:
    controller_host: "{{ platform_host }}"
    aap_token: "{{ aap_token }}"
    validate_certs: "{{ aap_validate_certs | default(true) }}"
    name: "{{ cur_image['name'] }}"
    image: "{{ cur_image['image'] }}"
    state: "absent"
  when:
    - cur_image['image'] not in config_images
    - (cur_image['image'] | split('/'))[1] not in aap_container_namespaces
    - cur_image['name'] not in aap_reserved_images
  loop: "{{ __aap_ee_images }}"
  loop_control:
    loop_var: cur_image
