---
- name: Get id of credential_type Container Registry
  ansible.builtin.set_fact:
    registry_type_id: "{{ __aap_credential_types | selectattr('namespace', 'eq', 'registry') | map(attribute='id') | first }}"

- name: Get a list of container registry credentials
  ansible.builtin.set_fact:
    container_credential: "{{ __aap_credentials | selectattr('credential_type', 'eq', registry_type_id | int) | first }}"

- name: Add the execution environments to the controller
  loop: "{{ aap_container_images | selectattr('type', 'eq', 'execution') }}"
  loop_control:
    loop_var: current_ee
    label: "{{ current_ee.image }}"
  awx.awx.execution_environment:
    controller_host: "{{ platform_host }}"
    aap_token: "{{ aap_token }}"
    validate_certs: "{{ aap_validate_certs | default(true) }}"
    name: "{{ current_ee.name }}"
    description: "{{ current_ee.description }}"
    image: "{{ aap_main_url }}/{{ current_ee.namespace }}/{{ current_ee.image }}:{{ current_ee.tag | default('latest') }}"
    credential: "{{ container_credential.name }}"
    state: present
